---

- hosts: all
  become: true
  remote_user: root
  tasks:
  - name: Install apache
    package:
      name: 
        - "httpd"
      state: present 
  - name: Starting up httpd
    service:
      name: httpd
      state: started
      enabled: yes 
  - name: permit traffic in default zone for https service
    firewalld:
      service: http   
      permanent: yes
      state: enabled
      #enabled: yes
  - name: copying .html file to webservers
    copy:
      src: /root/Ansible/files/site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  # - name: remove file
  #   file:
  #     path: /var/www/html/index.html
  #     sate: absent
    