  - name: installing httpd
    yum:
      name: "{{ httpd_package_name }}"
      state: latest
      
  - name: starting and enabling httpd
    service: 
      name: "{{ httpd_package_name }}"
      state: started
      enabled: yes