---
- name: installing httpd , opening port 80 , starting and enableing , adding a user
  hosts: web_serves
  become: true
  
  tasks:

  - name: installing httpd
    yum:
      name: "{{ httpd_package_name }}"
      state: latest

  - name: opening port 80
    firewalld:
      zone: public 
      service: http
      permanent: yes
      state: enabled 
      immediate: yes

  - name: starting and enabling httpd
    service: 
      name: "{{ httpd_package_name }}"
      state: started
      enabled: yes

  - name: create a user 
    user:
      name: ansible
      group: wheel 
      password: "{{ passwordx }}"
